### ISSUE TITLE
support speaker personal detail and profile image

### ISSUE THREAD

**Issue by fengmk2** [cnodejs/conf#5]
- Show detail infomation of speaker;
- speaker header image and github url or blog url.

**Comment by iwillwen** [comment]
Ok, I will send you later.

fengmk2 reply@reply.github.com编写：

**Comment by glennblock** [comment]
Add twitter/sina url also if available

**Comment by iwillwen** [comment]
I try to add twitter support, but the problem is the app can't send a POST request to the twitter's server.

**Comment by fengmk2** [comment]
@glennblock I think aliapp's server can't connect with twitter because the `GFW`.
But I'm trying the linode proxy to get it done.

**Comment by glennblock** [comment]
I mean just list their twitter account urls. Not that the site has to pull
actually from twitter.

On Mon, Jul 30, 2012 at 4:36 PM, Will Wen Gunn <
reply@reply.github.com

**Comment by iwillwen** [comment]
Oh I see, I am try to collect the local speakers' weibo url. And could you
help me to collect the twitter urls?

2012/7/30 Glenn Block <
reply@reply.github.com

> I mean just list their twitter account urls. Not that the site has to pull
> actually from twitter.
> 
> On Mon, Jul 30, 2012 at 4:36 PM, Will Wen Gunn <
> reply@reply.github.com
> 
> > wrote:
> > 
> > I try to add twitter support, but the problem was the app can't send a
> > POST request to the twitter's server.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/cnodejs/conf/issues/5#issuecomment-7362942
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/cnodejs/conf/issues/5#issuecomment-7363753

## 

_Will Wen Gunn 甘超阳 小问_
A Web Developer, Front-end Engineer, Server-side JavaScript
Developer(Node.js), Otaku, Framework Designer.

Weibo: http://weibo.com/iwillwen
Twitter: http://twitter.com/iwillwen
Blog: http://iwwen.me
Cure: iwwen
About Me: http://about.me/iwillwen

**Comment by glennblock** [comment]
Yes, I/Troy can handle local speakers twitter and blogs

On 7/30/12, Will Wen Gunn
reply@reply.github.com
wrote:

**Comment by iwillwen** [comment]
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=a5f7d5f0-fe86-e211-b16a
-d6233cd505ab&signedParameters=wNzeazeTLSlr6e3toNm12CNY3myU9yYMKSiMT1GWwO0.eyJlbW
FpbCI6InJlcGx5K2ktNTkwNjA5OC05NThlN2ZhMGFmOWMyYmI2YTI4MDVlMjRkNzkxY2JlMGIwODBiZmR
kLTczMTQyNEByZXBseS5naXRodWIuY29tIiwiZnJvbSI6ImE1ZjdkNWYwLWZlODYtZTIxMS1iMTZhLWQ2
MjMzY2Q1MDVhYiIsInRvIjoiNmM4ODM0YTYtYWM2Ny01YTFiLWEyMWUtODNiODU3OTkwZjRiIiwiaXNzd
WVkX2F0IjoiMTM2MjY1MjMxMyIsInZlciI6IjEiLCJwIjoiMyJ9&emailMessageId=6859acf0-fe86-
e211-909b-95c6b39b66a5&emailType=Invite&sdate=201303071031&utm_source=EmailInvite
&utm_medium=Email&emailLinkType=Logo>

Hi,

Become a part of your friend's network.

<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=a5f7d5f0-fe86-e211-b16a
-d6233cd505ab&signedParameters=wNzeazeTLSlr6e3toNm12CNY3myU9yYMKSiMT1GWwO0.eyJlbW
FpbCI6InJlcGx5K2ktNTkwNjA5OC05NThlN2ZhMGFmOWMyYmI2YTI4MDVlMjRkNzkxY2JlMGIwODBiZmR
kLTczMTQyNEByZXBseS5naXRodWIuY29tIiwiZnJvbSI6ImE1ZjdkNWYwLWZlODYtZTIxMS1iMTZhLWQ2
MjMzY2Q1MDVhYiIsInRvIjoiNmM4ODM0YTYtYWM2Ny01YTFiLWEyMWUtODNiODU3OTkwZjRiIiwiaXNzd
WVkX2F0IjoiMTM2MjY1MjMxMyIsInZlciI6IjEiLCJwIjoiMyJ9&emailMessageId=6859acf0-fe86-
e211-909b-95c6b39b66a5&emailType=Invite&sdate=201303071031&utm_source=EmailInvite
&utm_medium=Email&emailLinkType=ProfileThumb>

Will Wen Gunn
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=a5f7d5f0-fe86-e211-b16a
-d6233cd505ab&signedParameters=wNzeazeTLSlr6e3toNm12CNY3myU9yYMKSiMT1GWwO0.eyJlbW
FpbCI6InJlcGx5K2ktNTkwNjA5OC05NThlN2ZhMGFmOWMyYmI2YTI4MDVlMjRkNzkxY2JlMGIwODBiZmR
kLTczMTQyNEByZXBseS5naXRodWIuY29tIiwiZnJvbSI6ImE1ZjdkNWYwLWZlODYtZTIxMS1iMTZhLWQ2
MjMzY2Q1MDVhYiIsInRvIjoiNmM4ODM0YTYtYWM2Ny01YTFiLWEyMWUtODNiODU3OTkwZjRiIiwiaXNzd
WVkX2F0IjoiMTM2MjY1MjMxMyIsInZlciI6IjEiLCJwIjoiMyJ9&emailMessageId=6859acf0-fe86-
e211-909b-95c6b39b66a5&emailType=Invite&sdate=201303071031&utm_source=EmailInvite
&utm_medium=Email&emailLinkType=ProfileName>

Invite sent: 7 March, 2013

Continue
<http://www.skillpages.com/i/ftuf/emailinvitelanding?user=a5f7d5f0-fe86-e211-b16a
-d6233cd505ab&signedParameters=wNzeazeTLSlr6e3toNm12CNY3myU9yYMKSiMT1GWwO0.eyJlbW
FpbCI6InJlcGx5K2ktNTkwNjA5OC05NThlN2ZhMGFmOWMyYmI2YTI4MDVlMjRkNzkxY2JlMGIwODBiZmR
kLTczMTQyNEByZXBseS5naXRodWIuY29tIiwiZnJvbSI6ImE1ZjdkNWYwLWZlODYtZTIxMS1iMTZhLWQ2
MjMzY2Q1MDVhYiIsInRvIjoiNmM4ODM0YTYtYWM2Ny01YTFiLWEyMWUtODNiODU3OTkwZjRiIiwiaXNzd
WVkX2F0IjoiMTM2MjY1MjMxMyIsInZlciI6IjEiLCJwIjoiMyJ9&cnId=a5f7d5f0-fe86-e211-b16a-
d6233cd505ab&emailMessageId=6859acf0-fe86-e211-909b-95c6b39b66a5&emailType=Invite
&sdate=201303071031&utm_source=EmailInvite&utm_medium=Email&emailLinkType=MainCal
lToAction>

reply@reply.github.com
was invited to join SkillPages by Will Wen Gunn. To stop receiving emails from
SkillPages click here
<http://www.skillpages.com/i/account/unsubscribe?signedParameters=UFfX9opizO8mI3P
-2L8L2qCNoX55S5hh1b0WujvrKCY.eyJlbWFpbCI6InJlcGx5K2ktNTkwNjA5OC05NThlN2ZhMGFmOWMy
YmI2YTI4MDVlMjRkNzkxY2JlMGIwODBiZmRkLTczMTQyNEByZXBseS5naXRodWIuY29tIiwiaXNzdWVkX
2F0IjoiMTM2MjY1MjMxMyIsInZlciI6IjEiLCJwIjoiMCJ9&emailMessageId=6859acf0-fe86-e211
-909b-95c6b39b66a5&emailType=Invite&sdate=201303071031&utm_source=EmailInvite&utm
_medium=Email&emailLinkType=Unsubscribe> .

© 2013 SkillPages, Blackrock Business Park, Dublin, Ireland and 228 Hamilton
Avenue, 3rd Floor, Palo Alto, CA 94301.
